bancolombia/commons-jms

.github/workflows/main.yml
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/MQReactiveMessageListenerTest.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/config/MQListenerAnnotationProcessorTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/MQConnectionListenerTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/MQContextListenerTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/sender/MQMultiContextSenderSyncTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/sender/MQMultiContextSenderTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/utils/MQMessageListenerUtilsTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/utils/MQQueueUtilsTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/utils/MQTemporaryQueuesContainerImpTest.java
examples/mq-reactive/mq-reactive.gradle

remove the test assertion, because the thread is asynchronous

---

commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/security/SSLContextUtils.java
examples/mq-reactive/src/main/java/co/com/bancolombia/jms/sample/app/config/Config.java
gradle.properties

Add ssl context factory from jks

add ssl context utils to use with jks

---

commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/utils/MQUtils.java
gradle.properties

Features:
- Upgrade Spring Boot dependency
- Upgrade mq dependency
Fixes
- Change log level when trying to get queue manager name

upgrade spring dependencies

---

commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/utils/MQUtils.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/utils/MQUtilsTest.java
gradle.properties

Features:
- Extract queue manager from temporary queue
- Update dependencies

Extract queue manager from temporary queue, update dependencies

---

commons-jms-api/src/main/java/co/com/bancolombia/commons/jms/api/MQQueueManagerSetter.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSelectorListener.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSelectorListenerTest.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/models/MQListenerConfig.java
examples/mq-reactive-selector/src/main/java/co/com/bancolombia/jms/sample/selector/drivenadapters/MyMQSender.java
examples/mq-reactive-selector/src/main/resources/application.yaml
gradle.properties

Features:
- Auto save queue with queue manager assigned in the MQ queues container

auto save queue with queue manager assigned in the MQ queues container

---

commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSelectorListener.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/utils/MQUtils.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSelectorListenerTest.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/helper/JmsContextImpl.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/utils/MQUtilsTest.java
gradle.properties

Improvements:
- Resolve queue manager name through "XMSC_WMQ_RESOLVED_QUEUE_MANAGER" property.

Resolve connected queue manager from connection

---

build.gradle
gradle.properties
main.gradle

Features:
- Implementation for #26

feat: added dependency check plugin.

---

README.md
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSelectorListener.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSender.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQListenerAnnotationProcessor.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQProperties.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/proxy/InterfaceComponentProxyFactoryBean.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSelectorListenerTest.java
commons-jms-utils/commons-jms-utils.gradle
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQContextMessageSelectorListenerSync.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerSync.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/models/RetryableConfig.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/reconnect/AbstractJMSReconnectable.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/sender/MQMultiContextSenderSync.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/utils/MQMessageListenerUtils.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/utils/RetryableTask.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerSyncTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/sender/MQMultiContextSenderSyncTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/utils/MQMessageListenerUtilsTest.java
gradle.properties

The pull request contains the code to externalize the retry connection configuration.-

feat: External retry connection configuration

---

commons-jms-api/src/main/java/co/com/bancolombia/commons/jms/api/MQMessageSelectorListener.java
commons-jms-api/src/main/java/co/com/bancolombia/commons/jms/api/MQMessageSelectorListenerSync.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSelectorListener.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQContextMessageSelectorListenerSync.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListener.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerSync.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerSyncTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerTest.java
gradle.properties

Implements overload methods to get message by selectors

Allow custom selector

---

commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSelectorListener.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfigurationSelectorListenerTest.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/MQConnectionListener.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/MQContextListener.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/MQMultiConnectionListener.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQContextMessageSelectorListenerSync.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListener.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerSync.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/strategy/ContextPerMessageStrategy.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/strategy/ContextSharedStrategy.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/strategy/SelectorModeProvider.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/strategy/SelectorStrategy.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/models/MQListenerConfig.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/reconnect/AbstractJMSReconnectable.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/sender/MQContextSenderSync.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/utils/ReactiveReplyRouter.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/MQContextListenerTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/MQMultiConnectionListenerTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerSyncTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/reconnect/AbstractJMSReconnectableTest.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/sender/MQMultiContextSenderSyncTest.java
examples/mq-reactive-replier/src/main/resources/application.yaml
examples/mq-reactive-selector/src/main/java/co/com/bancolombia/jms/sample/selector/drivenadapters/MyMQSender.java
examples/mq-reactive-selector/src/main/resources/application.yaml
gradle.properties

Features:
- Use separated threads for reactive selector.
- Make an automatic retry gettting a message by selector with reconnection.
- Allow shared context and context by message.

Improve selector listener

---

commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/models/MQListenerConfig.java
examples/mq-reactive/src/main/java/co/com/bancolombia/sample/app/config/UseCasesConfig.java
examples/mq-reactive/src/main/java/co/com/bancolombia/sample/drivenadapters/reqreply/MyRequestReplyAdapter.java
examples/mq-reactive/src/main/java/co/com/bancolombia/sample/drivenadapters/reqreply/MyRequestReplySingleInstance.java
gradle.properties

Add listener for fixed queues without selector

Add new listener type

---

commons-jms-http-replier/src/main/java/co/com/bancolombia/commons/jms/http/replier/Utils.java
commons-jms-http-replier/src/test/java/co/com/bancolombia/commons/jms/http/replier/UtilsTest.java
gradle.properties

Fixes:
- Fix reading body from bytes messages

Fix bytes message read bytes message

---

.github/workflows/main.yml
.github/workflows/release.yml
.github/workflows/scorecards-analysis.yml
.github/workflows/secret-scanner.yml

fix(conditions): Add commit with github app and skip condition when automatic release

fix(conditions): Add commit with github app and skip condition when automatic release

---

commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfiguration.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQSpringResolver.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/factory/MQReqReplyFactory.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfiguracionTest.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/config/MQSpringResolverTest.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/config/utils/MQFactoryBeanTest.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQExecutorService.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListener.java
commons-jms-utils/src/test/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListenerTest.java

Fixes:
- fix(performance): Return to specific scheduler used in v1.3.0 for message selector

fix(performance): Return to specific scheduler used in v1.3.0 for message selector

---

commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/internal/listener/selector/MQMultiContextMessageSelectorListener.java

Fixes:
- fix(scheduler): Save single scheduler on selector instantiation

fix(scheduler): Save single scheduler on selector instantiation

---

commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/listeners/MQRequestReplySelector.java

MQRequestReplySelector getters

fix(selector): Add getter to use listener externally

---

.github/workflows/main.yml

Use github app only with main branch

build(conditions): Use github app only with main branch

---

commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/security/SSLContextUtils.java
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/security/SSLCredentials.java
main.gradle

Features:
- Create context from pems and add trustore from OS dirs

feat(sslcontext): Create context from pems and add trustore from OS dirs

---

.gitignore
commons-jms-utils/src/main/java/co/com/bancolombia/commons/jms/security/SSLContextUtils.java

Fixes:
- Ignore non certs lines

fix(sslcontext): ignore empty certs

---

README.md
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfiguration.java
commons-jms-mq/src/main/java/co/com/bancolombia/commons/jms/mq/config/health/MQListenerDisabledHealthIndicator.java
commons-jms-mq/src/test/java/co/com/bancolombia/commons/jms/mq/config/MQAutoconfiguracionTest.java
examples/mq-reactive/src/main/resources/application.yaml

Fixes:
- Add option to disable health indicator for MQ listeners

fix(health): Add option to disable health indicator for MQ listeners

---

main.gradle

fix(release): try to release new central repository

fix(release): try to release new central repository
